In [281]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [282]:
os.getcwd()

'E:\\Homework'

In [283]:
#Change to directory that contains the file
os.chdir(r"E:\Homework")

In [284]:
#Make pandas datframe
df = pd.read_csv("Croptype_ML.csv")

In [285]:
print(df)

         Apr       May       Jun       Jul       Aug       Sep       Oct  \
0   0.192446  0.191327  0.210436  0.265295  0.295329  0.286931  0.288937   
1   0.466576  0.599811  0.686571  0.681104  0.618238  0.610079  0.581589   
2   0.518384  0.571037  0.600181  0.594809  0.578448  0.575181  0.483160   
3   0.170497  0.237880  0.258929  0.278638  0.313335  0.296088  0.213707   
4   0.418736  0.518178  0.605978  0.662785  0.659698  0.625166  0.550201   
..       ...       ...       ...       ...       ...       ...       ...   
75  0.746553  0.758416  0.712478  0.656886  0.611732  0.533305  0.470771   
76  0.753838  0.691741  0.670499  0.721311  0.695586  0.503222  0.260167   
77  0.830652  0.805342  0.733612  0.678396  0.598218  0.515394  0.488396   
78  0.825922  0.795334  0.750655  0.689467  0.621405  0.413176  0.192420   
79  0.760352  0.752475  0.622442  0.382554  0.195805  0.196295  0.336552   

         Nov       Dec      CropType  
0   0.301711  0.314586         apple  
1   0.513

In [286]:
#Interpolate to fill missing values
res = df.interpolate()

In [287]:
#Factorize the column of croptype
factor = pd.factorize(res['CropType'])
res.CropType = factor[0]
definitions = factor[1]
print(res.CropType.head())
print(definitions)

0    0
1    0
2    0
3    0
4    0
Name: CropType, dtype: int64
Index(['apple', 'fallow', 'potato', 'alfalfa hay', 'wheat fallow'], dtype='object')


In [288]:
print(res)

         Apr       May       Jun       Jul       Aug       Sep       Oct  \
0   0.192446  0.191327  0.210436  0.265295  0.295329  0.286931  0.288937   
1   0.466576  0.599811  0.686571  0.681104  0.618238  0.610079  0.581589   
2   0.518384  0.571037  0.600181  0.594809  0.578448  0.575181  0.483160   
3   0.170497  0.237880  0.258929  0.278638  0.313335  0.296088  0.213707   
4   0.418736  0.518178  0.605978  0.662785  0.659698  0.625166  0.550201   
..       ...       ...       ...       ...       ...       ...       ...   
75  0.746553  0.758416  0.712478  0.656886  0.611732  0.533305  0.470771   
76  0.753838  0.691741  0.670499  0.721311  0.695586  0.503222  0.260167   
77  0.830652  0.805342  0.733612  0.678396  0.598218  0.515394  0.488396   
78  0.825922  0.795334  0.750655  0.689467  0.621405  0.413176  0.192420   
79  0.760352  0.752475  0.622442  0.382554  0.195805  0.196295  0.336552   

         Nov       Dec  CropType  
0   0.301711  0.314586         0  
1   0.513011  0.4

In [289]:
#importing the dataset
X = res.iloc[:, :-1].values
y = res.iloc[:, -1].values

In [290]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 4]


In [291]:
#splitting dataset into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [292]:
print(y_test)

[2 1 1 3 2 3 3 3 2 3 2 3 0 3 2 1 0 1 0 1]


In [293]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [294]:
#Training the random forest classification on the training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 15, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=15, random_state=0)

In [295]:
print(y_test)

[2 1 1 3 2 3 3 3 2 3 2 3 0 3 2 1 0 1 0 1]


In [296]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [297]:
print(y_pred)

[2 1 1 3 2 3 3 3 2 3 2 3 0 3 2 3 1 1 0 1]


In [298]:
#making predictions
#y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [1 1]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [0 0]
 [3 3]
 [2 2]
 [3 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]]


In [299]:
#displaying confusion_matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2 1 0 0]
 [0 4 0 1]
 [0 0 5 0]
 [0 0 0 7]]


0.9